language: python
sudo: enabled
cache:
  directories:
  - $HOME/.cache/pip
  - /tmp/cached/
python:
  - '3.5'
  - '3.6'
env:
  # needed to fix issues with boto during testing:
  # https://github.com/travis-ci/travis-ci/issues/7940
  global: BOTO_CONFIG=/dev/null
install:
  - pip install -r requirements.txt
  - pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_md-2.0.0/en_core_web_md-2.0.0.tar.gz --no-cache-dir > jnk
  - python -m spacy link en_core_web_md en
before_script:
  - mkdir $HOME/tmp
  - export TMPDIR=$HOME/tmp
script:
  - py.test test_nlu.py